### ISSUE TITLE
[mod compat request] GregTechCEu Modern (with AE2)

### ISSUE THREAD

**Issue by ANZUARIAKE0127** [npg418/uti-alsofluidsandchemicals#2]
![image](https://github.com/user-attachments/assets/768ce674-cc36-4b4e-9606-6e0f741390e8)
Mod: GregTechCEu Modern (v 1.4.0+)
Mod id: gtceu
Request Description: Support for GregTech CEu Modern (on AE2 terminals).
GregTech is almost forced to automate AE2 in some areas. Therefore, I kindly ask for your support in this matter. Luckily it works fine on JEI :)

詳細: AE2ターミナルにおけるGregTech CEu Modernのサポート
GregTechはAE2自動化がほぼ必須のようなきらいがありますので，追加していただければ幸いです．幸い、JEIでは問題なく動作します :)

**Comment by npg418** [comment]
了解です！
少し私生活が立て込んでいるのでしばらくお待ち下さい

**Comment by npg418** [comment]
tterrag1098/Registrate#31
どうやらgtceuの依存先であるRegistrateのバグのようです。
幸いMilestoneに追加されていますがこちら側でも対応できるかトライしてみます。

**Comment by npg418** [comment]
全く見当違いでした…
対応版をリリースしました! [release/1.1.3](https://github.com/npg418/uti-alsofluidsandchemicals/releases/tag/1.1.3)
CurseForgeにもアップロードしましたがApproveされるのに少し時間がかかります!
解決したとしてCloseします
